### ISSUE TITLE
[Question] - What proves that it's the fastest?

### ISSUE THREAD

**Issue by Olyno** [taojy123/valval#3]
Hi,
The current description of ``valval`` is "The fastest web framework in V language", but what proves that it's the fatest? Did you make any benchmark about it? I mean, there are some other V frameworks as [vex](https://github.com/nedpals/vex), and nothing tell me that ``valval`` is fatest.

Maybe create a benchmark about it?

Thanks for your work, Olyno

**Comment by taojy123** [comment]
Hi,
This is just a slogan, don't take it too seriously.
I have not make benchmark, but I think the code of `valval` is the purest to listen requests and handler responses, so I think `valval` run fastest, hahaha...
And I also say in the document, it means `people can develop a website more faster then other framework`, because it's so easy.

Thank you for your attention.

**Comment by Olyno** [comment]
Thanks for your honest reply 😃
